packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/stripe': ^1.0.0
  '@prisma/client': ^6.15.0
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  next: 16.0.0
  stripe: ^19.1.0
  tsdown: ^0.15.5
  zod: ^4.1.12
