packages:
  - apps/*
  - packages/*

catalog:
  '@aws-sdk/client-s3': ^3.823.0
  '@ai-sdk/fal': ^1.0.24
  '@better-auth/stripe': ^1.0.0
  '@prisma/client': ^7.0.0
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  '@upstash/redis': ^1.35.7
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  next: 16.0.7
  pg: ^8.14.1
  stripe: ^19.1.0
  tsdown: ^0.15.5
  zod: 4.1.12
