packages:
  - apps/*
  - packages/*

catalog:
  '@aws-sdk/client-s3': ^3.823.0
  '@aws-sdk/s3-request-presigner': ^3.823.0
  '@ai-sdk/fal': ^1.0.24
  '@better-auth/stripe': ^1.4.5
  '@prisma/client': ^7.0.0
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  '@upstash/redis': ^1.35.7
  better-auth: ^1.4.6
  dotenv: ^17.2.2
  next: 16.0.10
  pg: ^8.14.1
  stripe: ^20.0.0
  tsdown: ^0.17.3
  zod: 4.1.12
